# Generated by Django 4.2.7 on 2026-04-01 18:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('papers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicPerformance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attempts', models.IntegerField(default=0)),
                ('total_marks_possible', models.IntegerField(default=0)),
                ('total_marks_obtained', models.IntegerField(default=0)),
                ('accuracy', models.FloatField(default=0.0)),
                ('last_practiced', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_performances', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='papers.topic')),
            ],
            options={
                'db_table': 'topic_performances',
                'indexes': [models.Index(fields=['student', 'accuracy'], name='topic_perfo_student_c36e99_idx')],
                'unique_together': {('student', 'topic')},
            },
        ),
        migrations.CreateModel(
            name='DailyActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('questions_attempted', models.IntegerField(default=0)),
                ('time_spent_minutes', models.IntegerField(default=0)),
                ('subjects_practiced', models.JSONField(default=list)),
                ('accuracy_today', models.FloatField(default=0.0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'daily_activities',
                'ordering': ['-date'],
                'unique_together': {('student', 'date')},
            },
        ),
    ]
