# Generated by Django 4.2.7 on 2026-04-01 18:34

import cloudinary.models
import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('session', models.CharField(choices=[('May/June', 'May/June'), ('Oct/Nov', 'Oct/Nov'), ('Feb/March', 'Feb/March')], max_length=20)),
                ('paper_number', models.IntegerField(default=1)),
                ('variant', models.IntegerField(default=1)),
                ('total_marks', models.IntegerField(default=0)),
                ('pdf_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'papers',
                'ordering': ['-year', 'session'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('board', models.CharField(choices=[('CAIE', 'CAIE'), ('EDEXCEL', 'Edexcel')], default='CAIE', max_length=20)),
                ('level', models.CharField(choices=[('O_LEVEL', 'O Level'), ('A_LEVEL', 'A Level'), ('IGCSE', 'IGCSE')], default='O_LEVEL', max_length=20)),
                ('icon_url', models.URLField(blank=True)),
                ('color_hex', models.CharField(default='#4F8EF7', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'subjects',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('unit', models.CharField(blank=True, max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent_topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subtopics', to='papers.topic')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='papers.subject')),
            ],
            options={
                'db_table': 'topics',
                'ordering': ['order', 'name'],
                'unique_together': {('subject', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_number', models.CharField(max_length=20)),
                ('raw_question_number', models.CharField(blank=True, max_length=100)),
                ('text', models.TextField(blank=True)),
                ('unit', models.CharField(blank=True, max_length=200)),
                ('marks', models.IntegerField(default=1)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('has_image', models.BooleanField(default=False)),
                ('image_url', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='q_images')),
                ('has_parts', models.BooleanField(default=False)),
                ('marking_scheme', models.TextField(blank=True)),
                ('sub_topics', models.JSONField(blank=True, default=list)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('ai_confidence', models.FloatField(blank=True, null=True)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='papers.paper')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='papers.topic')),
            ],
            options={
                'db_table': 'questions',
                'ordering': ['paper', 'question_number'],
            },
        ),
        migrations.AddField(
            model_name='paper',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='papers', to='papers.subject'),
        ),
        migrations.CreateModel(
            name='QuestionPart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('part_label', models.CharField(max_length=10)),
                ('part_text', models.TextField(blank=True)),
                ('has_image', models.BooleanField(default=False)),
                ('image_url', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='part_images')),
                ('marking_answer', models.TextField(blank=True)),
                ('marks', models.IntegerField(default=1)),
                ('order', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_parts', to='papers.question')),
            ],
            options={
                'db_table': 'question_parts',
                'ordering': ['order', 'part_label'],
                'unique_together': {('question', 'part_label')},
            },
        ),
        migrations.AddIndex(
            model_name='question',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='question_search_gin'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['topic', 'difficulty'], name='q_topic_diff'),
        ),
        migrations.AlterUniqueTogether(
            name='paper',
            unique_together={('subject', 'year', 'session', 'paper_number', 'variant')},
        ),
    ]
