# Generated by Django 4.2.7 on 2026-04-01 18:34

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('papers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MockExam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('duration_minutes', models.IntegerField(default=60)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('total_marks', models.IntegerField(default=0)),
                ('obtained_marks', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ongoing', 'Ongoing'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('topic_breakdown', models.JSONField(blank=True, default=dict)),
                ('question_results', models.JSONField(blank=True, default=list)),
                ('ai_feedback', models.TextField(blank=True)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('questions', models.ManyToManyField(blank=True, to='papers.question')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mock_exams', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='papers.subject')),
            ],
            options={
                'db_table': 'mock_exams',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answer_text', models.TextField(blank=True)),
                ('answer_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='answers')),
                ('ai_marks', models.IntegerField(blank=True, null=True)),
                ('ai_feedback', models.TextField(blank=True)),
                ('improvement_tips', models.JSONField(blank=True, default=list)),
                ('score_percentage', models.FloatField(blank=True, null=True)),
                ('grading_status', models.CharField(choices=[('pending', 'Pending'), ('grading', 'Grading'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='papers.question')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'submissions',
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['student', 'submitted_at'], name='submissions_student_6bcf5e_idx'), models.Index(fields=['question', 'student'], name='submissions_questio_15afab_idx')],
            },
        ),
        migrations.CreateModel(
            name='MockExamAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answer_text', models.TextField(blank=True)),
                ('answer_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='exam_answers')),
                ('marks_obtained', models.IntegerField(blank=True, null=True)),
                ('ai_feedback', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='submissions.mockexam')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='papers.question')),
            ],
            options={
                'db_table': 'mock_exam_answers',
                'unique_together': {('exam', 'question')},
            },
        ),
    ]
