# Generated by Django 4.2.7 on 2026-04-01 18:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], max_length=20)),
                ('module', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'system_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['level', 'created_at'], name='system_logs_level_5a2647_idx')],
            },
        ),
        migrations.CreateModel(
            name='ScraperJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject_code', models.CharField(max_length=10)),
                ('year', models.CharField(max_length=4)),
                ('session', models.CharField(max_length=20)),
                ('paper_type', models.CharField(default='qp', max_length=5)),
                ('variant', models.CharField(max_length=5)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('downloading', 'Downloading'), ('extracting', 'Extracting'), ('classifying', 'Classifying'), ('saving', 'Saving'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('progress', models.IntegerField(default=0)),
                ('total_questions', models.IntegerField(default=0)),
                ('classified_questions', models.IntegerField(default=0)),
                ('result_file', models.JSONField(blank=True, default=list)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('initiated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'scraper_jobs',
                'ordering': ['-created_at'],
            },
        ),
    ]
